title = "Ana Luiza Vedovato"
baseURL = "https://alvedovato.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 25 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Ana Luiza Vedovato"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/custom.css"]
  favicon = "/images/avicon.png"
  site_logo = "/images/avwhite.png"
  description = "Welcome! I am Ana Luiza Vedovato and this is my academic website."
  facebook = ""
  twitter = "https://twitter.com/ALVedovato"
  instagram = ""
  youtube = ""
  github = "https://github.com/ALVedovato"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/ana-luiza-vedovato-733535156/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  body_classes = "bodoni bg-white"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/avrio.JPG"
  recent_posts_number = 1

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"